# Generated by Django 3.2.3 on 2021-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.CharField(choices=[('Friends', 'Only Friends'), ('Public', 'Public')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
