# Generated by Django 3.2.3 on 2021-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=1212121212, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
